name: 🎯 Epic
description: A large task with a tasklist
type: Epic
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the epic issue.
