name: 🏃🏻‍♂️ Task
description: A general task, that is not concerned with code or documentation.
type: Task
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the task.
